FROM quantumobject/docker-opensimulator
MAINTAINER Giovanni De Gasperis  @giodegas

RUN apt-get update && apt-get install -y tcpdump net-tools netcat vim

# Opensimulator
EXPOSE 9000/tcp
EXPOSE 9000/udp
